### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kousyougi** [SeonMe/openwrt-trojan#1]
我用 QEMU 跑 這個openwrt官網的印象檔
http://downloads.openwrt.org/releases/19.07.0-rc2/targets/x86/64/openwrt-19.07.0-rc2-x86-64-combined-ext4.img.gz

沒有做其他設定直接安裝這個IPK，顯示Segmentation fault。

 OpenWrt 19.07.0-rc2, r10775-db8345d8e4
 -----------------------------------------------------
root@OpenWrt:/# opkg install trojan_1.14.0-1_x86_64.ipk
[  456.031349] opkg[3606]: segfault at 7f7d77d13000 ip 00007f7d77ceffec sp 00007f7
d77c7ba38 error 4 in libc.so[7f7d77cb3000+49000]
Segmentation fault
root@OpenWrt:/# 

RAM有1G，只用了3%。
請問我可能是漏掉什麼東西了嗎？

謝謝

**Comment by SeonMe** [comment]
请更换正式版 19.07

**Comment by SeonMe** [comment]
> 我用QEMU跑这个openwrt官网的印象档
> [http://downloads.openwrt.org/releases/19.07.0-rc2/targets/x86/64/openwrt-19.07.0-rc2-x86-64-combined-ext4。 img.gz](http://downloads.openwrt.org/releases/19.07.0-rc2/targets/x86/64/openwrt-19.07.0-rc2-x86-64-combined-ext4.img.gz)
> 
> 没有做其他设定直接安装这个IPK，显示分割错误。
> 
> ## OpenWrt 19.07.0-rc2，r10775-db8345d8e4
> 根@ OpenWrt的：/＃opkg安装trojan_1.14.0-1_x86_64.ipk
> [456.031349] opkg [3606]：在段错误IP 7f7d77d13000 SP 00007f7d77ceffec 00007f7
> d77c7ba38在libc.so错误4 [7f7d77cb3000 + 49000]
> 分段故障
> 根@的OpenWrt：/＃
> 
> RAM有1G，只用了3％。
> 请问我可能是漏掉什么东西了吗？
> 
> 谢谢

**Comment by SeonMe** [comment]
> 我用QEMU跑这个openwrt官网的印象档
> [http://downloads.openwrt.org/releases/19.07.0-rc2/targets/x86/64/openwrt-19.07.0-rc2-x86-64-combined-ext4。 img.gz](http://downloads.openwrt.org/releases/19.07.0-rc2/targets/x86/64/openwrt-19.07.0-rc2-x86-64-combined-ext4.img.gz)
> 
> 没有做其他设定直接安装这个IPK，显示分割错误。
> 
> ## OpenWrt 19.07.0-rc2，r10775-db8345d8e4
> 根@ OpenWrt的：/＃opkg安装trojan_1.14.0-1_x86_64.ipk
> [456.031349] opkg [3606]：在段错误IP 7f7d77d13000 SP 00007f7d77ceffec 00007f7
> d77c7ba38在libc.so错误4 [7f7d77cb3000 + 49000]
> 分段故障
> 根@的OpenWrt：/＃
> 
> RAM有1G，只用了3％。
> 请问我可能是漏掉什么东西了吗？
> 
> 谢谢

请更新 OpenWRT 至 19.07.0 正式版本

**Comment by kousyougi** [comment]
OpenWrt 19.07.0, r10860-a3ffeb413b
更新了還是一樣出現

root@OpenWrt:/# opkg install trojan_1.14.0-1_x86_
[  133.082065] opkg[2373]: segfault at 7f5505e950
505dfca38 error 4 in libc.so[7f5505e35000+49000]
Segmentation fault

請問我是缺少那些套件嗎？

**Comment by SeonMe** [comment]
> OpenWrt 19.07.0, r10860-a3ffeb413b
> 更新了還是一樣出現
> 
> root@OpenWrt:/# opkg install trojan_1.14.0-1_x86_
> [ 133.082065] opkg[2373]: segfault at 7f5505e950
> 505dfca38 error 4 in libc.so[7f5505e35000+49000]
> Segmentation fault
> 
> 請問我是缺少那些套件嗎？

没遇到过，你可以试试安装刚刚编译的版本。

**Comment by kousyougi** [comment]
> > OpenWrt 19.07.0, r10860-a3ffeb413b
> > 更新了還是一樣出現
> > root@OpenWrt:/# opkg install trojan_1.14.0-1_x86_
> > [ 133.082065] opkg[2373]: segfault at 7f5505e950
> > 505dfca38 error 4 in libc.so[7f5505e35000+49000]
> > Segmentation fault
> > 請問我是缺少那些套件嗎？
> 
> 没遇到过，你可以试试安装刚刚编译的版本。
剛剛用新編譯的ipk，已經裝得上去了。
trojan_1.14.0-1_2020.1.21_x86_64.ipk

謝謝

**Comment by SeonMe** [comment]
> > > OpenWrt 19.07.0, r10860-a3ffeb413b
> > > 更新了還是一樣出現
> > > root@OpenWrt:/# opkg install trojan_1.14.0-1_x86_
> > > [ 133.082065] opkg[2373]: segfault at 7f5505e950
> > > 505dfca38 error 4 in libc.so[7f5505e35000+49000]
> > > Segmentation fault
> > > 請問我是缺少那些套件嗎？
> > 
> > 
> > 没遇到过，你可以试试安装刚刚编译的版本。
> > 剛剛用新編譯的ipk，已經裝得上去了。
> > trojan_1.14.0-1_2020.1.21_x86_64.ipk
> 
> 謝謝

enjoy :)
