### ISSUE TITLE
Openwrt 默认目录下面没有opt这个目录啊！

### ISSUE THREAD

**Issue by wazzx** [SeonMe/openwrt-trojan#3]
root@OpenWrt:~# mkdir /opt/shell && cd /opt/shell
mkdir: can't create directory '/opt/shell': No such file or directory
老大对于x86应该是可以mkdir /opt/shell的但是对于那些硬路由不行。本人wndr3700v4 openwrt19.07.2版本 这一步做不了

**Comment by SeonMe** [comment]
> root@OpenWrt:~# mkdir /opt/shell && cd /opt/shell
> mkdir: can't create directory '/opt/shell': No such file or directory
> 老大对于x86应该是可以mkdir /opt/shell的但是对于那些硬路由不行。本人wndr3700v4 openwrt19.07.2版本 这一步做不了

我是基于软路由来的哈，硬路由我不玩 OpenWRT
