### ISSUE TITLE
斐讯N1做软路由无法使用openwrt + trojan

### ISSUE THREAD

**Issue by pharrellyhy** [SeonMe/openwrt-trojan#5]
Hi, thanks for sharing. 

我的配置是用斐讯N1做软路由，使用openwrt里的ssr+/v2ray，google和youtube都能正常使用。用我自己搭的gcp + trojan，在openwrt里其他设置（网关，dhcp，dns）都不变的情况下，只是改成trojan节点，google和youtube都不能访问，国内网站没问题；在mac上使用trojan客户端倒是能正常访问，是dns被污染了么。用你这里的方法能解决么？谢谢～

**Comment by SeonMe** [comment]
> Hi, thanks for sharing.
> 
> 我的配置是用斐讯N1做软路由，使用openwrt里的ssr+/v2ray，google和youtube都能正常使用。用我自己搭的gcp + trojan，在openwrt里其他设置（网关，dhcp，dns）都不变的情况下，只是改成trojan节点，google和youtube都不能访问，国内网站没问题；在mac上使用trojan客户端倒是能正常访问，是dns被污染了么。用你这里的方法能解决么？谢谢～

只针对x86平台，其他恕不解答。
