### ISSUE TITLE
能否帮忙编译一个18.06.4 x86 64版本的

### ISSUE THREAD

**Issue by herozzm** [SeonMe/openwrt-trojan#6]
实在编译不出来

**Comment by SeonMe** [comment]
> 实在编译不出来

自己研究一下，挺简单的

**Comment by herozzm** [comment]
> > 实在编译不出来
> 
> 自己研究一下，挺简单的

我在虚拟机上编译，编译了两晚上，都没成功，每次要的时间太长，没法守在电脑边，每次都不知道什么原因未成功
